// main.dart
// ─────────────────────────────────────────────────────────────────────────────
// IMPORTANT: Before running, you must generate firebase_options.dart by running:
//   flutterfire configure
//
// If you haven't done that yet, follow STEP A below first.
// ─────────────────────────────────────────────────────────────────────────────
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'firebase_options.dart';          // ← generated by: flutterfire configure
import 'models/app_models.dart';
import 'services/notification_service.dart';

// Admin screens
import 'screens/admin/login_screen.dart'  as admin;
import 'screens/admin/dashboard_screen.dart';

// User screens
import 'screens/user/login_screen.dart'   as user;
import 'screens/user/auctions_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.dark,
  ));

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await NotificationService().init();

  runApp(const BiddingApp());
}

class BiddingApp extends StatelessWidget {
  const BiddingApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bidding System',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const RoleGateway(),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// RoleGateway — checks active Firebase session on launch
// ─────────────────────────────────────────────────────────────────────────────
class RoleGateway extends StatelessWidget {
  const RoleGateway({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const _SplashScreen();
        }
        if (snapshot.data == null) {
          return const _RoleSelectScreen();
        }
        return _SessionRouter(uid: snapshot.data!.uid);
      },
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// _SessionRouter — reads role from Firestore and routes accordingly
// ─────────────────────────────────────────────────────────────────────────────
class _SessionRouter extends StatelessWidget {
  final String uid;
  const _SessionRouter({required this.uid});

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<DocumentSnapshot>(
      future: FirebaseFirestore.instance.collection('users').doc(uid).get(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) return const _SplashScreen();

        if (!snapshot.data!.exists) {
          FirebaseAuth.instance.signOut();
          return const _RoleSelectScreen();
        }

        final data = snapshot.data!.data() as Map<String, dynamic>;
        final role = data['role'] == 'admin' ? UserRole.admin : UserRole.user;

        if (role == UserRole.admin) {
          return _AdminApp(home: const DashboardScreen());
        } else {
          return _UserApp(home: const AuctionsScreen());
        }
      },
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Role select screen
// ─────────────────────────────────────────────────────────────────────────────
class _RoleSelectScreen extends StatelessWidget {
  const _RoleSelectScreen();

  @override
  Widget build(BuildContext context) {
    final isWide = MediaQuery.of(context).size.width > 600;

    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: BoxConstraints(maxWidth: isWide ? 480 : double.infinity),
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 40),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  // Logo
                  Container(
                    width: 72,
                    height: 72,
                    decoration: BoxDecoration(
                      color: const Color(0xFF3B82F6),
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: const Icon(Icons.gavel_rounded,
                        color: Colors.white, size: 36),
                  ),
                  const SizedBox(height: 20),
                  const Text(
                    'BidForge',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 32,
                      fontWeight: FontWeight.w900,
                      letterSpacing: -1,
                    ),
                  ),
                  const SizedBox(height: 6),
                  const Text(
                    'Real-time auction platform',
                    style: TextStyle(color: Color(0xFF94A3B8), fontSize: 14),
                  ),

                  const SizedBox(height: 56),

                  _RoleButton(
                    icon: Icons.admin_panel_settings_rounded,
                    label: 'Admin Portal',
                    subtitle: 'Manage products & auctions',
                    color: const Color(0xFF1E40AF),
                    onTap: () => Navigator.of(context).push(MaterialPageRoute(
                      builder: (_) =>
                          _AdminApp(home: const admin.AdminLoginScreen()),
                    )),
                  ),

                  const SizedBox(height: 14),

                  _RoleButton(
                    icon: Icons.storefront_rounded,
                    label: 'Bidder App',
                    subtitle: 'Browse products & place bids',
                    color: const Color(0xFF059669),
                    onTap: () => Navigator.of(context).push(MaterialPageRoute(
                      builder: (_) =>
                          _UserApp(home: const user.UserLoginScreen()),
                    )),
                  ),

                  const SizedBox(height: 48),

                  const Text(
                    'Powered by Firebase · Flutter',
                    style: TextStyle(color: Color(0xFF475569), fontSize: 11),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Role button
// ─────────────────────────────────────────────────────────────────────────────
class _RoleButton extends StatelessWidget {
  final IconData icon;
  final String label, subtitle;
  final Color color;
  final VoidCallback onTap;

  const _RoleButton({
    required this.icon,
    required this.label,
    required this.subtitle,
    required this.color,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: color.withOpacity(0.12),
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: color.withOpacity(0.4)),
        ),
        child: Row(
          children: [
            Container(
              width: 52,
              height: 52,
              decoration: BoxDecoration(
                color: color,
                borderRadius: BorderRadius.circular(14),
              ),
              child: Icon(icon, color: Colors.white, size: 26),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(label,
                      style: const TextStyle(
                          color: Colors.white,
                          fontSize: 17,
                          fontWeight: FontWeight.w700)),
                  const SizedBox(height: 2),
                  Text(subtitle,
                      style: const TextStyle(
                          color: Color(0xFF94A3B8), fontSize: 12)),
                ],
              ),
            ),
            Icon(Icons.arrow_forward_ios_rounded, color: color, size: 16),
          ],
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Sub-app wrappers
// ─────────────────────────────────────────────────────────────────────────────
class _AdminApp extends StatelessWidget {
  final Widget home;
  const _AdminApp({required this.home});

  @override
  Widget build(BuildContext context) {
    // Import admin theme inline to avoid circular issues
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1E40AF)),
        scaffoldBackgroundColor: const Color(0xFFF1F5F9),
        fontFamily: 'Inter',
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          foregroundColor: Color(0xFF0F172A),
          elevation: 0,
          titleTextStyle: TextStyle(
            color: Color(0xFF0F172A),
            fontSize: 18,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      home: home,
    );
  }
}

class _UserApp extends StatelessWidget {
  final Widget home;
  const _UserApp({required this.home});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF3B82F6)),
        scaffoldBackgroundColor: const Color(0xFFF8FAFC),
        fontFamily: 'Inter',
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 0,
          centerTitle: true,
          titleTextStyle: TextStyle(
            fontSize: 17,
            fontWeight: FontWeight.w700,
            color: Color(0xFF0F172A),
          ),
        ),
      ),
      home: home,
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Splash
// ─────────────────────────────────────────────────────────────────────────────
class _SplashScreen extends StatelessWidget {
  const _SplashScreen();

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: Color(0xFF0F172A),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.gavel_rounded,
                color: Color(0xFF3B82F6), size: 48),
            SizedBox(height: 16),
            CircularProgressIndicator(
              color: Color(0xFF3B82F6),
              strokeWidth: 2.5,
            ),
          ],
        ),
      ),
    );
  }
}